### ISSUE TITLE
New website design (for discussion)

### ISSUE THREAD

**Issue by latentflip** [techmeetup/techmeetup.co.uk#11]
I know @benseven and @jarofgreen and I have been thinking about how to make improvements to the website, opening this for comments and discussion about what we can do.

Please add your thoughts! And if you want to help, let me know!

**Comment by latentflip** [comment]
My immediate thoughts:
- Improve language (more "learn", less "beer")
- Include some pictures of events
- Better description of what to expect, at the events, and how to get there, etc
- Easy to maintain list of previous talks/events
- Cleaner design
- Per event pages?

**Comment by MikeMcQuaid** [comment]
Videos!

**Comment by latentflip** [comment]
@mikemcquaid good idea!

**Comment by sherred** [comment]
FYI it's @ben_seven

**Comment by jarofgreen** [comment]
Per event pages, give each event some freedom. For some _EdinburghCought_ detailed directions on how to find the venue and how to actually get in the doors when you do.

**Comment by benseven** [comment]
In bullets:
- Multi-device site refactor, so that site layout and assets are served
  mobile-first, with a fluid multi-column layout kicking in at the
  appropriate point. I'm happy to lead the approach on this having built a
  number of performant responsive sites that have tested well across
  browsers, e.g. http://www.yarddigital.com and have a recipe I can
  happily explain to anyone else along the way.
- All graphic assets (i.e. non-photographic) are put together as SVG
  with a PNG fallback via https://github.com/filamentgroup/grunticon so
  that hi-dpi screens get crisp, sharp assets. We're using this on
  http://www.devicelab.org for all logos and icons.
- Bit of a visual refresh too, but the scope of this probably needs to
  be identified.
- Interested in new features Phil was mentioning too.

Having written this I can see there are 5 new messages below. Hopefully
this doesn't contradict anyone :)

B7

## Ben Seven

Identity & Print Design | Web Design & Build
http://www.benseven.co.uk
@ben_seven | +44 7746 2004 12 | hello@benseven.co.uk

**Comment by ijonas** [comment]
Areas for national as well as event-specific / local sponsors.

**Comment by decadecity** [comment]
Happy to help out with the build.

**Comment by jarofgreen** [comment]
See issue #3 for discussion about open tech calendar feeds

**Comment by latentflip** [comment]
Some inspiration: http://www.frontendlondon.co.uk/

**Comment by jarofgreen** [comment]
So I made a start. https://github.com/daleharvey/techmeetup/pull/13 Any comments are welcome, tweaks wanted, this doesn't have to be the final version.

**Comment by MikeMcQuaid** [comment]
#13 was merged, closing.
