### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by latentflip** [techmeetup/techmeetup.co.uk#12]
To make techmeetup more accessible to newcomers, I've been thinking about whether we should adopt a code of conduct. Not because anything has happened (that I'm aware of) but to set us in good stead for the future.

For reference, 
- Pycon's CoC: https://us.pycon.org/2012/codeofconduct/
- GeekFeminism's example CoC: http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

**Comment by MikeMcQuaid** [comment]
:+1:

**Comment by MikeMcQuaid** [comment]
Much better to get this stuff right before it's a problem.

**Comment by jarofgreen** [comment]
+1 Even just having a code sets the right tone even if we don't think we'll ever have to use it (finger's crossed)

**Comment by sherred** [comment]
Good idea, I'd like it to be short and succinct. Something along the lines - but better - of:
- Be awesome
- Don't be THAT person
- Bring the knowledge, leave the snark

**Comment by latentflip** [comment]
@sherred I think that might work as a tll;dr, but I think it needs to have policy behind it to hold much weight (we will ask you to leave if you are breaking this).

**Comment by jarofgreen** [comment]
Unfortunately others have tried short policies and it doesn't work. It needs details. Have to leave this conversion for now, may be back with links later

**Comment by RadioactiveMouse** [comment]
Personally I would like something in there that encourages ideas and feedback after the presentations but doesn't turn into a "well we do this much better at X".

Best example was during the one event at the new SkyScanner offices a while back where the poor presenter, who wasn't the technical founder, getting told he was unequivocally wrong for thinking he could try a different approach to funding. It became very hostile with several loud members of the audience chiming in and definitely will have made several people, including me, think twice about putting forward a talk.

**Comment by latentflip** [comment]
@RadioactiveMouse good point. I heard about that, made me sad :(

**Comment by johnd** [comment]
Coming at this from a Computer :( perspective, I think TechMeetup has different needs in a code of conduct than a new group like computer. You have people who are already deeply invested in TM as a community and feel a strong sense of ownership over it, but at the same time some of those people will be the ones contributing to when TM is hostile to outsiders and speakers.

I think the hard thing here is going to be finding the correct language to not only express the problem, but do it in a way that people identify it with their own behaviour themselves. (Instead of setting up the rules, and then having to call people when they break them without realising.)

I don't think the people attending TM want to be hostile or alienating, and don't realise that they are creating that environment, that idea that TM is a 'tough audience'. The real impact of a code of conduct could be getting them to see their behaviour from a different perspective.

**Comment by joejag** [comment]
Both of the given examples of Pycon and GeekFeminism seem good for covering harassment. I'm happy for either to be adopted.

Thinking from a past event perspective, I've not had any attendees raise harassment concerns directly. I've had an issue with one speaker who made a joke about women while speaking. I'd be in favour of sending a presenters Code of Conduct to speakers before the event.

There is a different culture to each of the meetups. If I think a member of the audience is trying to discredit or harass a speaker then I'll often diffuse the situation using humour or tell the audience member to save the criticism for the bar afterwards. I know in the Edinburgh TM it can get pretty scary sometimes. It's the reason I've never volunteered to speak there.

Thanks for raising this.

**Comment by jarofgreen** [comment]
I have put a placeholder in https://github.com/daleharvey/techmeetup/pull/13 until we agree a formal policy - it's on the about page.

**Comment by MikeMcQuaid** [comment]
This was done in https://github.com/techmeetup/techmeetup.co.uk/pull/22. Happy to make it apply to all the TechMeetups if there is buy-in.
